name: Create branch protection

on:
  workflow_dispatch: {}

jobs:
  create-branch-protection:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.INIT_TOKEN }}
          REQUEST_BODY: |
            {
              "required_status_checks": "strict",
              "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false,
              "required_conversation_resolution": true,
              "lock_branch": true,
              "enforce_admins": false
            }
        with:
          route: PUT /repos/{repository}/branches/{branch}/protection
          repository: ${{ github.repository }}
          branch: master
          body: ${{ env.REQUEST_BODY }}
