name: Create branch protection

on:
  workflow_dispatch: {}

jobs:
  create-branch-protection:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: "Create release"
      uses: "actions/github-script@v6"
      with:
        github-token: "${{ secrets.INIT_TOKEN }}"
        script: |
          try {
            const response = await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'master',
              required_status_checks: {
                strict: true,
                contexts: [
                  'continuous-integration/travis-ci'
                ]                
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1,
                require_last_push_approval: true,
                bypass_pull_request_allowances: {}
              },
              restrictions: {},
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true
            });

            core.exportVariable('URL', response.data.url);
          } catch (error) {
            core.setFailed(error.message);
          }      
