name: Add deploy labels

on:
  issue_comment:
    types: [created]

jobs:
  add-deploy-labels:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          const commentParams = "${{ github.event.comment.body }}".split(' ');
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [
              "cluster:" + commentParams[1],
              "valuesPath:" + commentParams[2]
            ]
          });
