name: Add deploy labels

on:
  issue_comment:
    types: [created]

jobs:
  add-deploy-labels:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    outputs:
      commentParams: ${{ steps.add-deploy-labels.outputs.result }}
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      id: add-deploy-labels
      with:
        result-encoding: string
        script: |
          const commentParams = "${{ github.event.comment.body }}".substring(1).replaceAll(" ", ":");
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [commentParams]
          });
          return commentParams;

  remove-deploy-labels:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/delete')
    runs-on: ubuntu-latest
    outputs:
      commentParams: ${{ steps.remove-deploy-labels.outputs.result }}
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      id: remove-deploy-labels
      with:
        result-encoding: string
        script: |
          const commentParams = "${{ github.event.comment.body }}".split(' ');
          const { data: labels } = await github.rest.issues.listLabelsOnIssue({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log(labels)
          let setLabels = []
          for (const label of labels) {
            if (!label.name.startsWith("deploy:" + commentParams[1])) {
              setLabels.push(label.name)
            }
          }
          github.rest.issues.setLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: setLabels
          });
          return commentParams;

  run-jenkins:
    permissions:
      pull-requests: write
    needs:
    - add-deploy-labels
    - remove-deploy-labels
    if: always() && contains(needs.*.result, 'success')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/sim-jenkins
      with:
        pr-id: ${{ github.event.issue.number }}
        deploy-label: ${{ contains(needs.add-deploy-labels.result, 'success') && needs.add-deploy-labels.outputs.commentParams || needs.remove-deploy-labels.outputs.commentParams }}
