name: Run release

on:
  pull_request:
    types: [labeled, edited, synchronize]

jobs:
  run-release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Run release
      run: |
        echo "${{ toJSON(github.event.pull_request.labels) }}"