name: Run jenkins

on:
  pull_request:
    types: [edited, synchronize]

jobs:
  get-deploy-labels:
    runs-on: ubuntu-latest
    outputs:
      deploy-labels: ${{ steps.get-deploy-labels.outputs.deploy-labels }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-deploy-labels
      id: get-deploy-labels
      with:
        pr-id: ${{ github.event.number }}

  run-jenkins:
    if: needs.get-deploy-labels.outputs.deploy-labels != '[]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: get-deploy-labels
    strategy:
      matrix:
        deploy-label: ${{ fromJSON(needs.get-deploy-labels.outputs.deploy-labels) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sim-jenkins
        with:
          pr-id: ${{ github.event.number }}
          deploy-label: ${{ matrix.deploy-label }}
